modLoader = "javafml"
loaderVersion = "*"
license = "All rights reserved"
issueTrackerURL = "https://github.com/henkelmax/advanced-mining-dimension/issues"
[[mods]]
modId = "mining_dimension"
version = "${mod_version}"
displayName = "Advanced Mining Dimension"
updateJSONURL = "https://update.maxhenkel.de/neoforge/mining_dimension"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension"
logoFile = "icon.png"
authors = "Max Henkel"
description = '''A dimension consisting just of caves'''
[[dependencies.mining_dimension]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_dependency}"
ordering = "NONE"
side = "BOTH"
[[dependencies.mining_dimension]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"