modLoader="javafml"
loaderVersion="${mod_loader_version}"
license="All rights reserved"
issueTrackerURL="https://github.com/henkelmax/advanced-mining-dimension/issues"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://maxhenkel.de/update/mining_dimension.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/advanced-mining-dimension"
authors="${mod_vendor}"
#logoFile="mining_dimension.png"
#credits=""
description='''A dimension consisting just of caves'''
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${mod_forge_version}"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mod_minecraft_version}]"
    ordering="NONE"
    side="BOTH"